name: "Composer version tests"

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - "main"

jobs:
  tests:
    name: "Composer versions"

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        composer-version:
          - "1.9.0"      # First v1 compatible release
          - "1.10.26"    # Last v1 release
          - "2.0.0"      # First v2 release
          - "2.1.0"      # Inversion strict/lax validation https://github.com/composer/composer/pull/9912
          - "2.1.1"      # Fix inversion strict/lax
          - "2.1.7"      # Added many type annotations internally
          - "2.1.10"     # Added type annotations to all classes
          - "2.2.0"      # First LTS version
          - "2.2.18"     # Last LTS version
          - "2.3.0"      # First 2.3.x version
          - "2.3.10"     # Last 2.3.x version
          - "2.4.0"      # First 2.4.x version
          - "2.4.2"      # Last 2.4.x version
          - "dev-main"
        os: [ ubuntu-20.04 ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.2"

      - name: "Install dependencies"
        run: "composer require --dev composer/composer:${{ matrix.composer-version }}"

      - name: "Run tests"
        run: "composer run phpunit"
