name: "Continuous Integration"

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  tests:
    name: "CI"

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        dependencies-preference:
          - "--prefer-lowest"
          - "--prefer-stable"
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        os: [ ubuntu-20.04 ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer update ${{ matrix.dependencies-preference }}"

      - name: "Run CI"
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: "composer run ci"
